apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo-backend
  template:
    metadata:
      labels:
        app: devops-demo-backend
    spec:
      containers:
      - name: devops-demo-backend
        image: sachinteenwal/devops-demo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
