apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: cloudnativedevops.wuaze.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-demo-backend
            port:
              number: 80
