apiVersion: v1
kind: Service
metadata:
  name: devops-demo-backend
spec:
  type: NodePort
  selector:
    app: devops-demo-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31458
