apiVersion: v1
kind: Service
metadata:
  name: End-TO-End-CI-CD-Pipeline-using-GitHub-Actions-service
spec:
  type: NodePort
  selector:
    app: End-TO-End-CI-CD-Pipeline-using-GitHub-Actions
  ports:
    - port: 80
      targetPort: 5000
